apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-backend-disk
  namespace: dencrypt
spec:
  capacity:
    storage: 1Gi
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /dev/loop12
    type: BlockDevice
